
Exception on /add [POST]
Traceback (most recent call last):
  File "/home/kishore/flask/gis/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kishore/flask/gis/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kishore/flask/gis/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kishore/flask/gis/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kishore/flask/gis/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./gis.py", line 58, in add
    f.write(lon+'|'+str(lat)+'|'+date+'|'+details+'\n')
TypeError: unsupported operand type(s) for +: 'float' and 'str'
